name: upload-artifact-with-cache

on:
  workflow_dispatch:

jobs:
  convert_and_upload_text_to_json:
    name: Convert and upload text to JSON
    runs-on: ubuntu-latest
    steps:
      - name: Restore JSON cache
        id: cache-json
        uses: actions/cache@v4
        with:
          path: archivo.json
          key: json-${{ hashFiles('archivo.json') }}

      - name: Generate JSON file
        if: steps.cache-json.outputs.cache-hit != 'true'
        uses: devops-actions/json-to-file@v1.0.4
        with:
          json: '{"name": "pipelines","activity": 3,"module": 2,"isRequired": false}'
          filename: 'archivo.json'

      - name: Check for changes in JSON
        run: |
          if [ "${{ steps.cache-json.outputs.cache-hit }}" == 'true' ]; then
            echo "No hay cambios en el JSON, usando cache existente"
          else
            echo "Contenido del JSON cambió, se generó nuevo archivo"
          fi

      - name: Upload JSON file
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: archivo.json
