name: upload-artifact

on: push

jobs:
  convert_and_upload_text_to_json:
    name: Convert and upload text to JSON
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore cache for JSON
        uses: actions/cache@v4
        with:
          path: archivo.json
          key: json-${{ hashFiles('archivo.json') }}

      - name: Generate JSON file
        if: steps.cache-json.outputs.cache-hit != 'true'
        uses: devops-actions/json-to-file@v1.0.4
        with:
          json: '{"name": "pipelines","activity": 3,"module": 2,"isRequired": false}'
          filename: 'archivo.json'

      - name: Save new cache if file changed
        if: steps.cache-json.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: archivo.json
          key: json-${{ hashFiles('archivo.json') }}

      - name: Upload JSON file
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: archivo.json
