name: cache-json

on:
  push: {}
  workflow_dispatch:
    inputs:
      txt:
        description: Nombre de la ejecución
        required: true
        type: string

jobs:
  cache-and-upload-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generar JSON
        uses: devops-actions/json-to-file@v1.0.4
        with:
          json: '{"name": "pipelines","activity": 3,"module": 2,"isRequired": false}'
          filename: 'archivo.json'

      - name: Restaurar cache si existe
        id: cache-json
        uses: actions/cache@v4
        with:
          path: archivo.json
          key: json-${{ hashFiles('archivo.json') }}

      - name: Resultado
        run: |
          if [ "${{ steps.cache-json.outputs.cache-hit }}" = "true" ]; then
            echo "El contenido NO cambió respecto al cache previo."
          else
            echo "El contenido CAMBIÓ y se generó un nuevo archivo."
          fi

      - name: Subir como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: artifact-json
          path: archivo.json
