name: cache-json-artifact

on: push

jobs:
  cache-and-upload-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore cache for JSON
        id: cache-json
        uses: actions/cache@v4
        with:
          path: archivo.json
          key: json-${{ hashFiles('archivo.json') }}

      - name: Generate JSON file
        if: steps.cache-json.outputs.cache-hit != 'true'
        uses: devops-actions/json-to-file@v1.0.4
        with:
          json: '{"name": "pipelines","activity": 3,"module": 2,"isRequired": false}'
          filename: 'archivo.json'

      - name: Save new cache if file changed
        if: steps.cache-json.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: archivo.json
          key: json-${{ hashFiles('archivo.json') }}

      - name: Check for changes in JSON
        run: |
          if [ "${{ steps.cache.outputs.cache-hit }}" = "true" ]; then
            echo "El contenido NO cambió respecto al cache previo."
          else
            echo "El contenido CAMBIÓ y se generó un nuevo archivo."
          fi

      - name: Upload JSON file
        uses: actions/upload-artifact@v4
        with:
          name: artifact-json
          path: archivo.json
