name: cache-json-artifact

on:
  workflow_dispatch:
    inputs:
      txt:
        description: Ingrese nombre de ejecución
        required: true
        type: string

jobs:
  cache-and-upload-json:
    runs-on: ubuntu-latest
    steps:
      - name: Set cache key based on JSON content
        run: |
          JSON_CONTENT='{"name":"pipelines","activity":3,"module":2,"isRequired":false}'
          echo "key=json-$(echo $JSON_CONTENT | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      - name: Restore cache for JSON
        uses: actions/cache@v4
        with:
          path: archivo.json
          key: ${{ steps.set-key.outputs.key }}

      - name: Generate JSON file
        if: steps.cache-json.outputs.cache-hit != 'true'
        uses: devops-actions/json-to-file@v1.0.4
        with:
          json: '{"name": "pipelines","activity": 3,"module": 2,"isRequired": false}'
          filename: 'archivo.json'

      - name: Result
        run: |
          if [ "${{ steps.cache-json.outputs.cache-hit }}" = "true" ]; then
            echo "El contenido NO cambió respecto al cache previo."
          else
            echo "El contenido CAMBIÓ y se generó un nuevo archivo."
          fi

      - name: Upload JSON file
        uses: actions/upload-artifact@v4
        with:
          name: artifact-json
          path: archivo.json
